export const DEFAULT_PERMISSIONS = [
  { code: 'user.read', name: 'View users' },
  { code: 'user.write', name: 'Manage users' },
  { code: 'role.read', name: 'View roles' },
  { code: 'role.write', name: 'Manage roles' },
  { code: 'permission.read', name: 'View permissions' },
  { code: 'permission.write', name: 'Manage permissions' },
  { code: 'content.read', name: 'View content' },
  { code: 'content.write', name: 'Manage content' },
  { code: 'post.read', name: 'View posts & articles' },
  { code: 'post.write', name: 'Manage posts & articles' },
  { code: 'product.read', name: 'View products' },
  { code: 'product.write', name: 'Manage products' },
  { code: 'booking.read', name: 'View bookings' },
  { code: 'booking.write', name: 'Manage bookings' },
  { code: 'destination.read', name: 'View destinations' },
  { code: 'destination.write', name: 'Manage destinations' },
  { code: 'property.read', name: 'View properties & stays' },
  { code: 'property.write', name: 'Manage properties & stays' },
  { code: 'room.read', name: 'View room types' },
  { code: 'room.write', name: 'Manage room types' },
  { code: 'restaurant.read', name: 'View restaurants' },
  { code: 'restaurant.write', name: 'Manage restaurants' },
  { code: 'experience.read', name: 'View experiences & tours' },
  { code: 'experience.write', name: 'Manage experiences & tours' },
  { code: 'promotion.read', name: 'View promotions' },
  { code: 'promotion.write', name: 'Manage promotions' },
  { code: 'review.read', name: 'View reviews & testimonials' },
  { code: 'review.write', name: 'Moderate reviews & testimonials' },
  { code: 'catalog.read', name: 'View catalog' },
  { code: 'catalog.write', name: 'Manage catalog' },
  { code: 'report.read', name: 'View reports' },
  { code: 'customer.read', name: 'View customers' },
  { code: 'customer.write', name: 'Manage customers' },
  { code: 'attendance.participants.read', name: 'View participants' },
  { code: 'attendance.participants.write', name: 'Manage participants' },
  { code: 'attendance.checkin.scan', name: 'Perform check-ins' },
  { code: 'attendance.reports.read', name: 'View attendance reports' },
  { code: 'dashboard.read', name: 'Access admin dashboard' },
  { code: 'dashboard.reset', name: 'Reset dashboard data' },
  { code: 'token.read', name: 'View API tokens' },
  { code: 'token.write', name: 'Revoke API tokens' },
];

export const DEFAULT_ROLES = [
  {
    code: 'admin',
    name: 'Administrator',
    description: 'Full system access',
    permissions: DEFAULT_PERMISSIONS.map((p) => p.code),
  },
  {
    code: 'editor',
    name: 'Content Editor',
    description: 'Manage content and catalog data',
    permissions: [
      'content.read',
      'content.write',
      'post.read',
      'post.write',
      'product.read',
      'product.write',
      'catalog.read',
      'catalog.write',
      'destination.read',
      'destination.write',
      'property.read',
      'property.write',
      'room.read',
      'room.write',
      'restaurant.read',
      'restaurant.write',
      'experience.read',
      'experience.write',
      'promotion.read',
      'promotion.write',
      'attendance.participants.read',
      'attendance.participants.write',
      'dashboard.read',
    ],
  },
  {
    code: 'support',
    name: 'Customer Support',
    description: 'Handle booking workflows and customer inquiries',
    permissions: [
      'booking.read',
      'booking.write',
      'user.read',
      'customer.read',
      'customer.write',
      'content.read',
      'promotion.read',
      'review.read',
      'review.write',
    ],
  },
  {
    code: 'scanner',
    name: 'Scanner',
    description: 'Scan participant QR/barcodes at events',
    permissions: ['attendance.checkin.scan'],
  },
];

export const DEFAULT_ADMIN = {
  email: process.env.DEFAULT_ADMIN_EMAIL ?? 'aloatist@gmail.com',
  password: process.env.DEFAULT_ADMIN_PASSWORD ?? 'ChangeMe123!',
  fullName: process.env.DEFAULT_ADMIN_NAME ?? 'System Administrator',
};
